# Generated by Django 3.2.25 on 2025-03-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='blog/default.jpg'),
            preserve_default=False,
        ),
    ]
